### ISSUE TITLE
PA Review: Word Lookup - Show

### ISSUE THREAD

**Issue by dbodow** [dbodow/lexicon#3]
[ x ] Backend: DB, model, controller, views
[ x ] Redux Loop: ajax, actions, reducer*
[ x ] Presentational Components*
[ x ] Styling
[ x ] Smooth, bug-free navigation

Reviewer testing instructions: while the search feature is in progress, navigate directly to the url you wish to see the search results for. e.g. to see the word `myopia` go directly to `#/lookup/myopia` while logged in.

**Comment by dobrynin** [comment]
Looks great; nicely done!
