### ISSUE TITLE
PA Review: Word Lookup - Search

### ISSUE THREAD

**Issue by dbodow** [dbodow/lexicon#4]
[ x ] Backend: DB, model, controller, views
[ x ] Redux Loop: ajax, actions, reducer
[ x ] Presentational Components
[ x ] Styling
[ x ] Smooth, bug-free navigation

Instructions for testing:
Be sure to test all cases for the search feature:
* Search returns no match
  * Try a nonsense search term like `asdkjfha`
* Search returns perfect match: expected behavior is to redirect to word show page
  * Try any dictionary word as the search term, e.g. `lexicon`
* Search returns match with multiple possible matches: expected behavior is to list best match and then an index of possible matches
  * Try `lexi` as a search term

**Comment by dobrynin** [comment]
All set!
