### ISSUE TITLE
PA Review: Lists

### ISSUE THREAD

**Issue by dbodow** [dbodow/lexicon#7]
[ x ] Backend: DB, model, controller, views
[ x ] Redux Loop: ajax, actions, reducer
[ x ] Presentational Components
[ x ] Styling
[ x ] Smooth, bug-free navigation

**Comment by dobrynin** [comment]
List creation doesn't seem to work on the live site?

**Comment by dbodow** [comment]
@dobrynin  Can you describe the input types that didn't word? I just checked the live site and two lists seem to have been created:
![screenshot-2017-11-30 lexicon](https://user-images.githubusercontent.com/4065355/33449674-51224aec-d5be-11e7-9072-5880a4acc4c1.png)

**Comment by dbodow** [comment]
Updated list creation to allow en-dashes and apostrophes. Ready for re-evaluation

**Comment by dobrynin** [comment]
Should I be able to update a list?

**Comment by dobrynin** [comment]
Looks good!
